# Generated by Django 5.2.7 on 2025-10-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Administrative'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('KITCHEN', 'Kitchen'), ('SECURITY', 'Security')], default='ADMINISTRATIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
