# Generated by Django 5.2.7 on 2025-10-11 11:38

from django.db import migrations


def fix_duplicate_emails(apps, schema_editor):
    """Fix duplicate email addresses by adding a suffix to duplicates"""
    Student = apps.get_model('core', 'Student')
    Staff = apps.get_model('core', 'Staff')
    
    # Handle Student duplicates
    seen_emails = set()
    for student in Student.objects.all().order_by('student_id'):
        if student.email in seen_emails:
            # Add a suffix to make it unique
            counter = 1
            original_email = student.email
            base_email = original_email.split('@')[0]
            domain = original_email.split('@')[1]
            while Student.objects.filter(email=student.email).exists():
                student.email = f"{base_email}{counter}@{domain}"
                counter += 1
            student.save()
        seen_emails.add(student.email)
    
    # Handle Staff duplicates
    seen_emails = set()
    for staff in Staff.objects.all().order_by('staff_id'):
        if staff.email in seen_emails:
            # Add a suffix to make it unique
            counter = 1
            original_email = staff.email
            base_email = original_email.split('@')[0]
            domain = original_email.split('@')[1]
            while Staff.objects.filter(email=staff.email).exists():
                staff.email = f"{base_email}{counter}@{domain}"
                counter += 1
            staff.save()
        seen_emails.add(staff.email)


def reverse_fix_duplicate_emails(apps, schema_editor):
    """Reverse migration - cannot be easily reversed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staff_category_alter_staff_email_alter_student_email'),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_emails, reverse_fix_duplicate_emails),
    ]