# Generated by Django 5.2.8 on 2025-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_duplicate_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('BOOKING', 'Booking'), ('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('UTILITIES', 'Utilities'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
